### PR TITLE
Fix SHA-512 implementation

### LINKED ISSUE #60: Make digest pass tests for vectors from NIST for longer messages
Now SHA2 implementations do not pass all of the tests from NIST documents, they have problems with hashing messages longer than one block. Those longer test vectors can be found on:
- http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA224.pdf
- http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA256.pdf
- http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA384.pdf
- http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA512.pdf
- http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA512_224.pdf
- http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA512_256.pdf

Current implementation does not check those and when added, does not pass them for bigger hashes (SHA-384, SHA-512, and when added, SHA-512/224 and SHA-512/256).

### PR DESCRIPTION
**Pull request by hauleth**
Closes #60

### CODE REVIEW

**Comment by hauleth** [comment]
@homu r=silmeth

**Comment by briansmith** [comment]
What was the problem? Was it really the difference between regular integers and wrapping integers, or something else? It is hard to tell from the commit because there are so many changes in it.

**Comment by hauleth** [comment]
64-bit SHA-2 use 128-bit length in bits in padding. This implementation store message length in `u64` and multiply it by 8 when needed (implemented as shift by 3). Error was caused by not leaving enough space for 128-bit length.

[This snippet will explain it better](https://github.com/libOctavo/octavo/pull/68/files#diff-2d72d9b1ceda144d6128c1745faba42eL302). So when last block length was greater than 119 bytes then there should be additional block filled with `0` except for last 8 bytes, in invalid code additional block was filled only when last block length was greater than 123 bytes.

**Comment by briansmith** [comment]
Thanks for the info!

**Pull request merged**
