### PR TITLE
Extract modules into independent crates

### PR DESCRIPTION
**Pull request by hauleth**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4b20e88f6fdf3d1fdf96ce00715f3dfc14e11dbf
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/libOctavo/octavo/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ac8b6e71b2e96394949da4c8d2d688b7e1ee9e96
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: d500e068cfdefa2a46e04ce6c08a3c68c50f2057
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/libOctavo/octavo/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ac8b6e71b2e96394949da4c8d2d688b7e1ee9e96
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 339c05755a812a49121ded2937d526b0f8eb2071
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/libOctavo/octavo/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by hauleth** [comment]
@homu r+

**Pull request merged**
