### PR TITLE
Add benchmarks for digests

### PR DESCRIPTION
**Pull request by hauleth**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 0771653a7516b0322e31bc8cd0a4c4d023142148
  - Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/libOctavo/octavo/blob/master/CONTRIBUTING.md

---

This message was auto-generated by https://gitcop.com

**Comment by hauleth** [comment]
@homu r+

**Comment by hauleth** [comment]
@briansmith updated in #40

**Comment by briansmith** [comment]
> Moving all computation to initialization is impossible (as there is no data) and very hard for finalization (not enough memory for big files).

Sure, but in theory an implementation could have, say, a 1MB internal buffer, in which case the benchmarks would reduce to measuring `memcpy` for the smaller input sizes. In particular, and more realistically, in my implementation, I've been considering using a 1024 bit (128 byte) buffer, regardless of the algorithm. This would make a comparison of the `$bytes == 16` and `$bytes == 128` cases meaningless for my implementation.

**Comment by hauleth** [comment]
Actually yes, it is possible, but this is unavoidable. In any case if I want to cheat I could just create bigger buffer. Using block size as benchmark default allow me to check how fast in general my implementation is and how have I improved between versions. It isn't done for sake of comparison between crypto libraries (I think that yours briansmith/crypto-bench is great place for that comparision).

**Pull request merged**
