### PR TITLE
chore(misc): change GetBadges shield in README.md

### PR DESCRIPTION
**Pull request by justi**
New GetBadges shield proposition

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: b90f7829f7e49df0047b135edc02ebcd03638fde
  - Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, revert, bench**

Guidelines are available at https://github.com/libOctavo/octavo/blob/master/CONTRIBUTING.md

---

This message was auto-generated by https://gitcop.com

**Comment by justi** [comment]
Doc says that 'chore' is a valid type, so...

**Comment by hauleth** [comment]
Doesn't matter :) Thanks for PR.

**Comment by justi** [comment]
:+1:

**Pull request merged**
