### PR TITLE
overflowing_add has been depreciated.

### PR DESCRIPTION
**Pull request by ghost**
This fixes the issue that overflow_add was removed. That broke the Blake2.rs module in the Octavo-Digest module.

Also have you considered breaking these into separate git repos?

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request
- Commit: 3f0454fe76e2a7b927237c7364e79ce1aaff959d
  - Commits must be in the following format: **%{type}(%{scope}): %{description}**
  - Your subject line is longer than 72 characters

Guidelines are available at https://github.com/libOctavo/octavo/blob/master/CONTRIBUTING.md

---

This message was auto-generated by https://gitcop.com

**Comment by hauleth** [comment]
I have considered splitting it to separate crates, but for now it is much easier for me to keep everything in one repo. In future probably this will be moved to separate repos.

About that overflowing add it is shame as now this implementation doesn't truly conform definition, but I will probably find solution to that.

Thanks for noticing.

**Comment by hauleth** [comment]
@homu r+

**Comment by lambda-fairy** [comment]
[`overflowing_add()` doesn't seem deprecated to me.](https://doc.rust-lang.org/nightly/std/primitive.u32.html#method.overflowing_add)

What's the source for that claim?

**Comment by hauleth** [comment]
It seem that there was short period when this was deprecated. Probably erroneously.

To be reverted.

**Pull request merged**
